name: Deploy to Windows Server via SSH

on:
  push:
    branches:
      - develop
      - testing
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set environment variable based on branch
      - name: Set environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "ENV=development" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "testing" ]]; then
            echo "ENV=testing" >> $GITHUB_ENV
          else
            echo "ENV=production" >> $GITHUB_ENV

      # Step 3: Copy files and run commands via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.6.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          timeout: 30s
          script: |
            echo "Removing old files..."
            rm -rf C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Backend/*
            rm -rf C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Frontend/*

            echo "Uploading Backend..."
            scp -r ./Ticketing-Management-System-Backend-/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Backend/

            echo "Uploading Frontend..."
            scp -r ./Ticketing-Management-System-Frontend/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Frontend/

            echo "Deployment completed!"
