name: Deploy to Windows Server

on:
  push:
    branches:
      - develop
      - testing
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set environment variable based on branch
      - name: Set environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "ENV=development" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF##*/}" == "testing" ]]; then
            echo "ENV=testing" >> $GITHUB_ENV
          else
            echo "ENV=production" >> $GITHUB_ENV

      # Step 3: Install WinSCP
      - name: Install WinSCP
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://winscp.net/download/WinSCP-5.21.10-Automation.zip -O WinSCP.zip
          unzip WinSCP.zip -d WinSCP

      # Step 4: Upload Backend & Frontend using WinSCP
      - name: Upload files via WinSCP
        run: |
          ./WinSCP/WinSCP.com /command ^
            "open sftp://${{ secrets.SERVER_USER }}:${{ secrets.SERVER_PASSWORD }}@${{ secrets.SERVER_HOST }}:22" ^
            "option batch abort" ^
            "option confirm off" ^
            "put -delete Ticketing-Management-System-Backend-/* C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Backend/" ^
            "put -delete Ticketing-Management-System-Frontend/* C:/github/ticketing-system/${ENV}/psba-ticket-management-portal/Frontend/" ^
            "exit"

      # Step 5: Optional — run your deploy PowerShell script remotely
      - name: Run remote PowerShell deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            powershell -NoProfile -ExecutionPolicy Bypass -File "C:\github\ticketing-system\deploy_scripts\deploy.ps1" -env $ENV
